version: "3.5"

services:
  range_api:
    image: ${PROJECT}-${ENVIRONMENT}-api-img
    container_name: ${PROJECT}-${ENVIRONMENT}-api
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./src:/home/nodejs/app/src
      - ./scripts:/home/nodejs/app/scripts
    environment:
      - PORT=${API_PORT}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_HOST=${POSTGRESQL_HOST_DOCKER}
      - NODE_ENV=${ENVIRONMENT}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT_DOCKER}
    networks:
      - local
  db:
    image: ${PROJECT}-${ENVIRONMENT}-postgress-img
    container_name: ${PROJECT}-${ENVIRONMENT}-db
    build:
     context: ./services/db
     dockerfile: Dockerfile
     args:
      - PORT:${POSTGRESQL_PORT_DOCKER}
    ports:
     - ${POSTGRESQL_PORT_DOCKER}:${POSTGRESQL_PORT_DOCKER}
    environment:
     - POSTGRES_USER=${POSTGRESQL_USER}
     - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
     - POSTGRES_DB=${POSTGRESQL_DATABASE}
    networks:
      - local
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  local:
    driver: bridge
    name: ${PROJECT}-${ENVIRONMENT}-network
volumes:
  postgres:
    name: ${PROJECT}-${ENVIRONMENT}-vol-postgres